name: ChaletTest

on: [push, pull_request]

jobs:
  # build:
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       os: [ubuntu-latest, macos-latest, windows-latest]

  #   runs-on: ${{ matrix.os }}



  build_version:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        # os: [ubuntu-latest] , 

    runs-on: ${{ matrix.os }}

    steps:
      - name: Get Chalet
        uses: dimitre/get-chalet@v2
      - name: Is this love?
        shell: bash
        run: |
          ./chalet/build/**/chalet --version
          ln -s ./chalet/build/**/chalet .
          ./chalet --version